### ISSUE TITLE
DatabaseError: Forbidden when doing parallel queries through Promise.all (javascript)

### ISSUE THREAD

**Issue by chronark** [mattrobenolt/ps-http-sim#7] opened 2023-12-20 13:07 UTC
I have not yet traced this all the way to the end, but when running tests against the proxy, all requests that include a `count` query are resulting in `DatabaseError: Forbidden`

The same tests pass when I use a real planetscale db.

An example drizzle query that fails is:
```ts
  db
        .select({ count: sql<string>`count(*)` })
        .from(schema.keys)
        .where(and(eq(schema.keys.keyAuthId, api.keyAuthId), isNull(schema.keys.deletedAt))),
 ```
 
 
 I'll try to dig a little deeper in the coming days

**Comment by chronark** [comment] 2023-12-20 13:25
Ok scratch that, my tests are passing when I run all db calls sequentially, if I use `Promise.all` to run them in parallel I get the mentioned error

**Comment by mattrobenolt** [comment] 2023-12-20 15:08
Oh, so now that you say this, this is a feature not a bug!

The issue is using the same session/connection in parallel. This is not good. I explicitly chose to make that error here since the behavior in PlanetScsle is nondeterministic and should be avoided. So the fact that this is erroring for you is pointing out a bug in your code.

For parallelism you need to use discrete connection objects. It's much harder for us to prevent this in PlanetScale itself and I've brought up that we should try and prevent this inside of database-js somehow.

I have a bunch of thoughts on https://github.com/planetscale/database-js/issues/139

See: https://github.com/mattrobenolt/ps-http-sim/issues/1

**Comment by mattrobenolt** [comment] 2023-12-20 15:12
And to be clear, by "connection" I mean explicitly one of these: https://github.com/planetscale/database-js/blob/main/src/index.ts#L179

This cannot be shared with concurrency deterministically.

Maybe this is more an issue with Drizzle? I'm actually not sure how any of this works there, nor am I too well versed in the JS ecosystem.

**Comment by chronark** [comment] 2023-12-20 15:30
Oooh ok. let me dig into this and get back to you.

Thank you!

**Comment by mattrobenolt** [comment] 2023-12-20 18:06
I'm going to close this for the time being since this is definitely intentional design that purposefully deviates from what PlanetScale does in production. The fact that folks hit this cements that we might need to either document this better or figure out how Drizzle is doing this incorrectly? Either way, it's definitely showcasing incorrect behavior from the client.

**Closed** 2023-12-20 20:21 UTC

**Comment by McPizza0** [comment] 2024-01-02 16:12
I'm hitting the same thing when multiple queries are processed in quick succession
docker logs: `planetscale-simulator-proxy  | 2h46m45.503765968s |WARN| session already in use caller="ps-http-sim/main.go:241"`

also using drizzle

My thoughts:
Since this works fine in production (PS-cloud), could this be changed to match production rather than optimal use?

**Comment by mattrobenolt** [comment] 2024-01-02 16:14
Then Drizzle is doing something wrong. I strongly would prefer to keep this behavior. The fact that people are hitting this is showing bugs in software. So either Drizzle or your application is wrong and saying this works against PlanetScale is mostly wrong too. It's wrong in the sense that the behavior is undefined and unpredictable. It might "work" for some cases, but others will be very wrong.

**Comment by mattrobenolt** [comment] 2024-01-02 16:16
And by "quick succession" this is suggesting you're using connections serially, which isn't what this error is about. This is about using requests in parallel without a new session. Unless you can prove otherwise and there's a bug in my code here detecting this behavior.

**Comment by mattrobenolt** [comment] 2024-01-02 16:19
If anything I could be open to adding a CLI flag to make this behave more like production and be unpredictable behavior. Something like `-yes-i-want-undefined-behavior-with-parallel-queries`.

**Comment by McPizza0** [comment] 2024-01-02 16:22
Thats fair
as you mentioned before, maybe this is something ps/js driver should handle
drizzle just passes sql commands to the planetscale js driver, and looking at the docs for the driver, theres no mention of creating a new connection object per query.

Ill try a raw replication with ps/js directly to rule out drizzle

**Comment by mattrobenolt** [comment] 2024-01-02 16:25
Yeah, I sorta agree/disagree still. It's complex. There's not a ton we can do in the driver itself. I think we should figure out how to make it more difficult to do the wrong thing somehow.

This is honestly what I liked about this error. It does expose misuse rather than masking over it.

**Comment by McPizza0** [comment] 2024-01-02 17:00
you are entirely correct
I tested with a large number of queries running in parralel directly with `@planetscale/database` and it worked perfectly fine. A new connection session was created for each query.
So this is a drizzle issue where its re-using the same connection for multiple queries.

Will reach out to them

**Comment by McPizza0** [comment] 2024-01-16 23:07
confirmed working 100%
used this repo for testing [McPizza0/drizzle-ps-concurrency-test](https://github.com/McPizza0/drizzle-ps-concurrency-test)

nice job @mattrobenolt
